# Define a versão do Docker Compose. A versão '3.8' é moderna e recomendada.
version: '3.8'

# Define a lista de serviços (containers) que compõem sua aplicação.
services:
  # O nome do nosso serviço. Pode ser qualquer nome, como 'app', 'client' ou 'frontend'.
  frontend:
    # Instrução para construir a imagem.
    # O '.' indica que o Docker Compose deve procurar o 'Dockerfile' no diretório atual.
    build: .
    # Define um nome para o container para fácil identificação.
    container_name: nkw-flow-frontend
    # Mapeia a porta 8080 da sua máquina (host) para a porta 80 do container (onde o Nginx está rodando).
    # O formato é "HOST:CONTAINER"
    ports:
      - "8080:80"