version: '3.8'

services:
  frontend:
    build: .
    container_name: nkw-flow-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      # Caso use variáveis para comunicar com o back-end
      - VITE_API_NODE_URL=http://backend:3000

  backend:
    build:
      context: ../NKW-FLOW-Node  # Caminho relativo ao Dockerfile do backend
    container_name: nkw-flow-backend
    ports:
      - "3000:3000"
    volumes:
      - ../NKW-FLOW-Node:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  default:
    name: nkw-network
